[project]
name = "chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "kagglehub>=0.3.10",
    "streamlit>=1.43.2",
    "transformers>=4.49.0",
    "uvicorn>=0.34.0",
    "torch>=2.2.2"
]
